# Use postgres/example user/password credentials
# for docs: https://hub.docker.com/_/postgres
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    volume: 
      - ./docker-data/db-data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      ports: 
        - 5432: 5432 # maps local port to container port
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080